image: edbizarro/bitbucket-pipelines-php7

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install rsync -y
            - composer install
            - yarn install
            - yarn prod
            - yarn rsync:staging